services:
  - type: web
    name: service-web
    env: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/atran/letterboxd-list-radarr.git
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: service-redis
          property: connectionString
      
  - type: redis
    name: service-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu
